image:
  repository: ghcr.io/hudsoncoutinho/honeybr
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources: {}

rules:
  sensitive_paths:
    - "/etc/shadow"
    - "/root/.ssh/id_rsa"
  suspicious_ports:
    - 4444
    - 1337
