apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: honeybr
spec:
  selector:
    matchLabels:
      app: honeybr
  template:
    metadata:
      labels:
        app: honeybr
    spec:
      serviceAccountName: honeybr
      hostPID: true
      containers:
        - name: honeybr
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          securityContext:
            privileged: {{ .Values.securityContext.privileged }}
          command: ["honeybr"]
          args: ["--rules=/etc/honeybr/rules.yaml"]
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: rules
              mountPath: /etc/honeybr
            {{- if .Values.hostMounts.tracing }}
            - name: tracing
              mountPath: /sys/kernel/tracing
              readOnly: true
            {{- end }}
            {{- if .Values.hostMounts.debug }}
            - name: debugfs
              mountPath: /sys/kernel/debug
              readOnly: true
            {{- end }}
      volumes:
        - name: rules
          configMap:
            name: honeybr-rules
        {{- if .Values.hostMounts.tracing }}
        - name: tracing
          hostPath:
            path: /sys/kernel/tracing
            type: Directory
        {{- end }}
        {{- if .Values.hostMounts.debug }}
        - name: debugfs
          hostPath:
            path: /sys/kernel/debug
            type: Directory
        {{- end }}
